// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefineEmit: typeof import('./src/components/DefineEmit.vue')['default']
    DefineProps: typeof import('./src/components/DefineProps.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotsAttrs: typeof import('./src/components/SlotsAttrs.vue')['default']
  }
}

export {}
